name: Deploy Site

on:
  release:
    types: [created]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Clean
        run: rm -r .git |
             rm -r .github |
             rm -f LICENSE |
             rm -f README.md
      
      - name: FTP Mirror
        uses: modern-dev/ftp-mirror@v2
        with:
          server: ${{secrets.FTP_SERVER}}
          user: ${{secrets.FTP_USER}}
          password: ${{secrets.FTP_PASSWORD}}
          local_dir: ./
          remote_dir: ${{secrets.REMOTE_DIR}}
          delete: true
          exclude: "/LICENSE /README.md /.github/ /.git/"
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: site
          path: "./"
          retention-days: 90
